name: Build & Release

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go-version: 
          - "1.16"
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Note the fetch-depth: 0 option on the Checkout workflow step. It is required for the change log to work correctly.
  
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  # inspired by https://blog.ediri.io/build-trust-with-signing-your-cli-binary-and-container
  release:
    needs: build
    env:
      #DOCKER_CLI_EXPERIMENTAL: "enabled"
      #UPX_VERSION: "3.96"
      COSIGN_KEY_LOCATION: "/tmp/cosign.key"
    runs-on: ubuntu-latest
    #if: success() && startsWith(github.ref, 'refs/tags/')
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.0.0'

      - name: Install Cosign private key
        run: 'echo "$COSIGN_KEY" > $COSIGN_KEY_LOCATION'
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@56f5b77f7fa4a8fe068bf22b732ec036cc9bc13f # using commit hash instead of 'v2' because this uses the GITHUB_TOKEN, see https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          GO_VERSION: 1.16
      
      # - name: set version as env
      #   run: |
      #     tag=$(git describe --tags --abbrev=0 | tr --delete v)
      #     echo "version=$tag" >> $GITHUB_ENV

      # - name: Sign the image
      #   run: |
      #     echo -n "${{secrets.COSIGN_PASSWORD}}" | cosign sign -key $COSIGN_KEY_LOCATION ghcr.io/hslatman/mud-cli:${{ env.version }}-amd64

